Repository microsoft/react-native-code-push, pull requests merged in 2020-06, with the labels that each got.

#1675 Redux Saga URL corrected
  README.md
Labels: documentation

#1710 default JWT should be 3.0.0-beta.12 not 3.0.0-beta.7
  CodePush.podspec
Labels: investigating

#1801 add overloaded type for CodePush function that accepts a React Component
  typings/react-native-code-push.d.ts
Labels: enhancement

#1880 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#1888 Fix capitalization of GitHub org
  .github/ISSUE_TEMPLATE.md
  CodePush.podspec
  README.md
  android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
  android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java
  android/codepush.gradle
  code-push-plugin-testing-framework/package.json
  docs/api-js.md
  docs/multi-deployment-testing-android.md
  docs/multi-deployment-testing-ios.md
  docs/setup-android.md
  docs/setup-ios.md
  package.json
  request-fetch-adapter.js
  scripts/generateBundledResourcesHash.js
  scripts/tools/linkToolsIos.js
Labels: documentation
