Repository microsoft/react-native-code-push, pull requests merged in 2020-10, with the labels that each got.

#1940 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#1954 Fix Xcode 12 compatibility.
  CodePush.podspec
Labels: compatibility, investigating

#1962 [Tests] Replace equal with strictEqual
  test/test.ts
Labels: tests
